In [2]:
import pandas as pd
import numpy as np 
import pickle
import ast
import joblib

In [3]:
with open('model_ada_model.pkl', 'rb') as file_2:
  model_ada_model= joblib.load(file_2)

with open('model_scaler.pkl', 'rb') as file_3:
  model_scaler=joblib.load(file_3)

with open('list_num_cols.txt', 'rb') as file_4:
  num_cols= joblib.load(file_4)

with open('list_cat_cols.txt', 'rb') as file_5:
  cat_cols= joblib.load(file_5)

In [4]:
np.random.seed(2895)
age = np.random.randint(40, 96, size=30)
creatinine_phosphokinase = np.random.randint(23, 7862, size=30)
anaemia = np.random.choice([0, 1], size=30)
serum_creatinine = np.random.choice([1.3 , 2.1 , 2.7 , 1.4 , 1.  , 1.2 , 2.5 , 5.  , 1.6 , 1.83, 1.7 ,
       0.9 , 0.8 , 0.5 , 0.7 , 1.1 , 3.  , 2.2 , 0.75, 1.18, 2.3 , 0.6 ,
       1.9 , 3.2 , 1.5 , 6.8 , 9.  , 4.4 , 2.9 , 2.4 , 3.5 , 2.  , 3.8 ,
       9.4 , 3.4 , 1.8 , 4.  , 5.8 , 3.7 , 6.1], size=30)
high_blood_pressure = np.random.choice([0,1], size=30)
smoking = np.random.choice([0, 1], size=30)
data_inf = pd.DataFrame({'age': age, 'creatinine_phosphokinase': creatinine_phosphokinase, 'anaemia': anaemia, 'serum_creatinine':serum_creatinine, 'high_blood_pressure': high_blood_pressure,'smoking':smoking })
print(data_inf)

    age  creatinine_phosphokinase  anaemia  serum_creatinine  \
0    45                      1769        0              3.40
1    83                      2376        0              3.50
2    89                      4258        1              1.00
3    80                      2803        1              0.70
4    77                       605        0              3.50
5    86                      4452        1              2.00
6    65                        44        1              3.70
7    61                      6902        1              2.30
8    79                      7165        1              1.83
9    45                      2986        1              1.60
10   66                       156        0              2.50
11   73                      7115        0              3.80
12   76                      7514        0              1.70
13   78                      6183        1              6.80
14   60                      4068        0              3.50
15   52                      2167        0              0.90
16   43                       468        1              3.50
17   49                      6565        0              2.70
18   68                      7797        1              9.40
19   62                      3134        0              1.10
20   79                       959        0              3.00
21   84                      6793        1              6.10
22   71                      7496        0              0.60
23   61                      7250        1              6.80
24   72                      6968        0              6.80
25   68                      7202        1              2.40
26   74                      1959        0              1.20
27   89                      3864        0              6.10
28   53                       406        0              9.00
29   85                      7728        1              2.40

    high_blood_pressure  smoking
0                     0        0
1                     0        1
2                     1        0
3                     0        0
4                     0        1
5                     0        1
6                     0        0
7                     1        1
8                     1        0
9                     0        1
10                    1        0
11                    1        0
12                    1        1
13                    1        1
14                    1        1
15                    1        1
16                    0        1
17                    1        0
18                    0        1
19                    0        1
20                    0        0
21                    0        0
22                    1        0
23                    1        1
24                    1        1
25                    0        0
26                    1        0
27                    1        0
28                    1        1
29                    1        1

In [5]:
data_inf_num = data_inf[num_cols]
data_inf_cat = data_inf[cat_cols]

In [6]:
data_inf_num_scaled = model_scaler.transform(data_inf_num)
data_inf_cat_encoded = data_inf_cat

In [7]:
data_inf_final = np.concatenate([data_inf_num_scaled, data_inf_cat], axis=1)

## Making Prediction

In [9]:
y_pred_inf = model_ada_model.predict(data_inf_final)
y_pred_inf

array([0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
predict = pd.DataFrame(y_pred_inf, columns=["Prediction"])

In [11]:
result = pd.concat([data_inf, pd.DataFrame(y_pred_inf, columns=["Prediction Death Event"])], axis=1)

In [12]:
result

,age,creatinine_phosphokinase,anaemia,serum_creatinine,high_blood_pressure,smoking,Prediction Death Event
0,45,1769,0,3.40,0,0,0
1,83,2376,0,3.50,0,1,0
2,89,4258,1,1.00,1,0,1
3,80,2803,1,0.70,0,0,0
4,77,605,0,3.50,0,1,0
5,86,4452,1,2.00,0,1,0
6,65,44,1,3.70,0,0,1
7,61,6902,1,2.30,1,1,1
8,79,7165,1,1.83,1,0,1
9,45,2986,1,1.60,0,1,0
10,66,156,0,2.50,1,0,1
11,73,7115,0,3.80,1,0,1
12,76,7514,0,1.70,1,1,1
13,78,6183,1,6.80,1,1,1
14,60,4068,0,3.50,1,1,0
15,52,2167,0,0.90,1,1,0
16,43,468,1,3.50,0,1,1
17,49,6565,0,2.70,1,0,1
18,68,7797,1,9.40,0,1,1
19,62,3134,0,1.10,0,1,0
20,79,959,0,3.00,0,0,1
21,84,6793,1,6.10,0,0,1
22,71,7496,0,0.60,1,0,1
23,61,7250,1,6.80,1,1,1
24,72,6968,0,6.80,1,1,1
25,68,7202,1,2.40,0,0,1
26,74,1959,0,1.20,1,0,1
27,89,3864,0,6.10,1,0,1
28,53,406,0,9.00,1,1,1
29,85,7728,1,2.40,1,1,1